### ISSUE TITLE
Support for Perl

### ISSUE THREAD

**Issue by xanni** [CoatiSoftware/SourcetrailDB#22]
I have created the Perl sourcetraildb module using SWIG.  PPI can be used to parse the Perl AST.

**Comment by mlangkabel** [comment]
Nice! Where is the binding? Can you create a pull request for it?

**Comment by xanni** [comment]
I'll create a pull request tomorrow.  It still needs a dynamically linked libsourcetraildb.so rather than the static libsourcetraildb.a otherwise I would have to create a statically linked Perl binary and I'd rather not do it that way.

**Comment by xanni** [comment]
Pull request created: https://github.com/CoatiSoftware/SourcetrailDB/pull/23

**Comment by mlangkabel** [comment]
Perl bindings are available with merge of pull request #34.

**Comment by zmughal** [comment]
I wanted to note that @xanni's indexer at <https://github.com/xanni/SourcetrailPerlIndexer> may need to get mentioned here under [Supported Languages](https://www.sourcetrail.com/documentation/#SupportedLanguages).

**Comment by mlangkabel** [comment]
Wow! Did not know about that project. Thank you very much for bringing it up! I will link it here in the readme. And if the project is already in a usable state, we may even integrate it with Sourcetrail directly (so that no custom sourcegroup is required anymore).

**Comment by zmughal** [comment]
That sounds great!

I have some patches in my fork of it as well to improve support for some syntax extensions that are provided through modules. I'll see if I can clean them up and submit the changes.

By the way, when you get a chance, could you take a look at #38 and #39? I got the Windows build working with Strawberry Perl.
