### ISSUE TITLE
How to read .srctrldb？

### ISSUE THREAD

**Issue by liaozhijia** [CoatiSoftware/SourcetrailDB#25]
How to read .srctrldb？Is there a command to get the internal data

**Comment by mlangkabel** [comment]
Currently the SourcetrailDB project does not offer an API for reading the database.

The `SourcetrailDBWriter` class provides the interface for saving data to the database. 

For the interface for reading, we imaging a `SourcetrailDBReader` class that provides generic methods like `getAllSymbols()`, `getAllSymbolLocations()`, etc.

**Comment by liaozhijia** [comment]
> Currently the SourcetrailDB project does not offer an API for reading the database.
> 
> The `SourcetrailDBWriter` class provides the interface for saving data to the database.
> 
> For the interface for reading, we imaging a `SourcetrailDBReader` class that provides generic methods like `getAllSymbols()`, `getAllSymbolLocations()`, etc.

OK，Thank you！

**Comment by liaozhijia** [comment]
> Currently the SourcetrailDB project does not offer an API for reading the database.
> 
> The `SourcetrailDBWriter` class provides the interface for saving data to the database.
> 
> For the interface for reading, we imaging a `SourcetrailDBReader` class that provides generic methods like `getAllSymbols()`, `getAllSymbolLocations()`, etc.

I did not find SourcetrailDBReader in the project

**Comment by mlangkabel** [comment]
Sorry if I was a little bit unclear. I wrote "we imagine" to indicate that it is not yet implemented ;)

**Comment by liaozhijia** [comment]
> Sorry if I was a little bit unclear. I wrote "we imagine" to indicate that it is not yet implemented ;)

OK，I know，thank you very much！

**Comment by fxomomi** [comment]
The .srctrldb file is actualy a .sqlite database file and can be inspected using the DB Browser for SQLite.
