### ISSUE TITLE
Meaning of edge type and node type in .srctrldb?

### ISSUE THREAD

**Issue by liaozhijia** [CoatiSoftware/SourcetrailDB#26]
Sorry, my English is not very good. I use Google Translate to translate Chinese into English, and it may not be clear. Here are my questions:
I used Sqllite to open the srctrldb file and found two data tables, node and edge. They contain the "type" field. I would like to ask, what does 1,4,8,512 in the edge table mean? And what does the content of the type field in the node table mean?

**Comment by mlangkabel** [comment]
Hi, you can find that information here:
Edge type: https://github.com/CoatiSoftware/SourcetrailDB/blob/master/core/include/EdgeKind.h#L31
Node type: https://github.com/CoatiSoftware/SourcetrailDB/blob/master/core/include/NodeKind.h#L25
