### ISSUE TITLE
NameHierarchy api complexity

### ISSUE THREAD

**Issue by chq-matteo** [CoatiSoftware/SourcetrailDB#3]
Hi, thank you for open sourcing a library to interact with the db

 I'm having trouble with the NameHierarchy structure.

Right now, to keep track of class -> method relationships, I have to track (and update!) with a separate data structure every NameHierarchy so that they will show up nicely grouped in Sourcetrail.

Wouldn't it be easier to allow developers to manage this use case with References (that is creating an edge) so that the resulting hierarchy will be implicit?

Even in https://github.com/CoatiSoftware/SourcetrailPythonIndexer/blob/master/indexer.py#L394 the NameHierarchy related code makes up 1/8 th of the code base.

With other languages it gets even worse!

I can't see any advantage with the current api pushing the complexity onto every new Language Backend rather than taking the toll in the frontend

**Comment by chq-matteo** [comment]
Ok I see a point with the current state if one has an advanced parser

**Comment by mlangkabel** [comment]
Hi @chq-matteo, yes, NameHierarchies are a little bit tricky and at first we even considered not to add them to the SourcetrailDB interface, for the sake of simplicity. But we figured that they are a required part. 

Lets consider some Python code that gets indexed. The code defines multiple modules, and let's say two of those modules (e.g. `foo` and `bar`) each define a function called `run()`. And now you index another function `main()` that calls one of these `run()` methods. When recording this call, you need to tell SourcetrailDB exactly that `foo.run()` has been called by `main` and the call edge that is displayed by Sourcetrail's UI will go from `main` to `foo.run()` and not to `bar.run()`.

This is done with the NameHierarchy. When parsing some code, you can usually derive the full name of a symbol somehow. This allows you to record references between symbols without being required to parse the definition of those symbols beforehand and also without storing any IDs for any symbols in some other data structure while parsing. Whenever you want to record a reference, just find out the full name (which is unique for that symbol) and you are good to go :)

**Comment by chq-matteo** [comment]
Yeah I think it will be proven to be a good idea in the long run
