### ISSUE TITLE
Typo: "Ambiuous" instead of "Ambiguous" used in multiple method signatures

### ISSUE THREAD

**Issue by LouisStAmour** [CoatiSoftware/SourcetrailDB#8]
For example: https://github.com/CoatiSoftware/SourcetrailDB/commit/49e8458d6db10bc1c0f7358107dfb6c0a6f624e3#diff-e265df4e0fdad58edad87694c8140a4cR365

In my TypeScript/Node implementation, I corrected it in the publicly-facing signature, but it of course still shows up in the C++ call: https://github.com/LouisStAmour/sourcetraildb/blob/master/Writer.cc#L317

**Comment by mlangkabel** [comment]
Fixed with merge of pull request #37.
